export interface State {
    isWindowsConsole: boolean
}

export const IS_WINDOWS_CONSOLE_CHECKBOX_ID = "IS_WINDOWS_CONSOLE_CHECKBOX_ID";
export const BUILD_WINDOWS_BUTTON_ID = "BUILD_WINDOWS_BUTTON_ID";
export const BUILD_LINUX_BUTTON_ID = "BUILD_LINUX_BUTTON_ID";

export const SET_STATE_COMMAND = "SET_STATE_COMMAND";
export const BUILD_WINDOWS_COMMAND = "BUILD_WINDOWS_COMMAND";
export const BUILD_LINUX_COMMAND = "BUILD_LINUX_COMMAND";
